# Generated by Django 2.2.19 on 2021-12-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211211_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
