# Generated by Django 2.2.9 on 2021-12-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20211215_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='t2t',
            field=models.TextField(null=True),
        ),
    ]
