# Generated by Django 2.2.9 on 2021-12-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_t2t'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='t2t',
        ),
    ]
